### PR TITLE
Consistent capitalization in MATL Editor

### PR DESCRIPTION
**Pull request by zrksyd**

### CODE REVIEW

**Comment by ScanMountGoat** [comment]
Good catch. For consistency, each button and menu button should capitalize the first word and every major word similar to how book titles work. Words like "the" or "and" should be lowercase. I think there may be a few more places where I messed up the capitalization.

**Comment by zrksyd** [comment]
Okay I changed it to match that.

**Comment by zrksyd** [comment]
(Decided to put this here to avoid a second pull request. I can retract it if need be.)

**Comment by ScanMountGoat** [comment]
Looks good. Thanks. In the future, please put unrelated changes in separate pull requests even if the changes are small. This makes it easier for me to review the changes individually.

**Pull request merged**
